// Expanded NSE stock universe — Nifty 50 + Nifty Next 50 + Nifty Midcap 50
// 150 stocks across all major sectors
// capType based on NSE classification as of 2025

const STOCK_UNIVERSE = [

  // ── NIFTY 50 ────────────────────────────────────────────────────────────────

  // Banking & Finance
  { ticker: 'HDFCBANK',   name: 'HDFC Bank',                    sector: 'Banking',        capType: 'Large Cap' },
  { ticker: 'ICICIBANK',  name: 'ICICI Bank',                   sector: 'Banking',        capType: 'Large Cap' },
  { ticker: 'SBIN',       name: 'State Bank of India',          sector: 'Banking',        capType: 'Large Cap' },
  { ticker: 'KOTAKBANK',  name: 'Kotak Mahindra Bank',          sector: 'Banking',        capType: 'Large Cap' },
  { ticker: 'AXISBANK',   name: 'Axis Bank',                    sector: 'Banking',        capType: 'Large Cap' },
  { ticker: 'BAJFINANCE', name: 'Bajaj Finance',                sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'BAJAJFINSV', name: 'Bajaj Finserv',                sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'HDFCLIFE',   name: 'HDFC Life Insurance',          sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'SBILIFE',    name: 'SBI Life Insurance',           sector: 'Finance',        capType: 'Large Cap' },

  // IT
  { ticker: 'TCS',        name: 'Tata Consultancy Services',    sector: 'IT',             capType: 'Large Cap' },
  { ticker: 'INFY',       name: 'Infosys',                      sector: 'IT',             capType: 'Large Cap' },
  { ticker: 'WIPRO',      name: 'Wipro',                        sector: 'IT',             capType: 'Large Cap' },
  { ticker: 'HCLTECH',    name: 'HCL Technologies',             sector: 'IT',             capType: 'Large Cap' },
  { ticker: 'TECHM',      name: 'Tech Mahindra',                sector: 'IT',             capType: 'Large Cap' },
  { ticker: 'LTIM',       name: 'LTIMindtree',                  sector: 'IT',             capType: 'Large Cap' },

  // Pharma & Healthcare
  { ticker: 'SUNPHARMA',  name: 'Sun Pharmaceutical',           sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'DRREDDY',    name: "Dr. Reddy's Laboratories",     sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'CIPLA',      name: 'Cipla',                        sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'DIVISLAB',   name: "Divi's Laboratories",          sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'APOLLOHOSP', name: 'Apollo Hospitals',             sector: 'Healthcare',     capType: 'Large Cap' },

  // Energy
  { ticker: 'RELIANCE',   name: 'Reliance Industries',          sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'ONGC',       name: 'Oil & Natural Gas Corp',       sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'POWERGRID',  name: 'Power Grid Corp',              sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'NTPC',       name: 'NTPC',                         sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'ADANIGREEN', name: 'Adani Green Energy',           sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'ADANIPORTS', name: 'Adani Ports & SEZ',            sector: 'Infrastructure', capType: 'Large Cap' },
  { ticker: 'ADANIENT',   name: 'Adani Enterprises',            sector: 'Conglomerate',   capType: 'Large Cap' },
  { ticker: 'BPCL',       name: 'Bharat Petroleum',             sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'IOC',        name: 'Indian Oil Corporation',       sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'COALINDIA',  name: 'Coal India',                   sector: 'Energy',         capType: 'Large Cap' },

  // Auto
  { ticker: 'MARUTI',     name: 'Maruti Suzuki',                sector: 'Auto',           capType: 'Large Cap' },
  { ticker: 'TATAMOTORS', name: 'Tata Motors',                  sector: 'Auto',           capType: 'Large Cap' },
  { ticker: 'M&M',        name: 'Mahindra & Mahindra',          sector: 'Auto',           capType: 'Large Cap' },
  { ticker: 'BAJAJ-AUTO', name: 'Bajaj Auto',                   sector: 'Auto',           capType: 'Large Cap' },
  { ticker: 'EICHERMOT',  name: 'Eicher Motors',                sector: 'Auto',           capType: 'Large Cap' },
  { ticker: 'HEROMOTOCO', name: 'Hero MotoCorp',                sector: 'Auto',           capType: 'Large Cap' },

  // FMCG
  { ticker: 'HINDUNILVR', name: 'Hindustan Unilever',           sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'ITC',        name: 'ITC',                          sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'NESTLEIND',  name: 'Nestle India',                 sector: 'FMCG',           capType: 'Large Cap' },

  // Metals
  { ticker: 'TATASTEEL',  name: 'Tata Steel',                   sector: 'Metals',         capType: 'Large Cap' },
  { ticker: 'JSWSTEEL',   name: 'JSW Steel',                    sector: 'Metals',         capType: 'Large Cap' },
  { ticker: 'HINDALCO',   name: 'Hindalco Industries',          sector: 'Metals',         capType: 'Large Cap' },

  // Telecom & Infra
  { ticker: 'BHARTIARTL', name: 'Bharti Airtel',                sector: 'Telecom',        capType: 'Large Cap' },
  { ticker: 'LT',         name: 'Larsen & Toubro',              sector: 'Infrastructure', capType: 'Large Cap' },
  { ticker: 'ULTRACEMCO', name: 'UltraTech Cement',             sector: 'Infrastructure', capType: 'Large Cap' },
  { ticker: 'GRASIM',     name: 'Grasim Industries',            sector: 'Conglomerate',   capType: 'Large Cap' },
  { ticker: 'INDUSINDBK', name: 'IndusInd Bank',                sector: 'Banking',        capType: 'Large Cap' },
  { ticker: 'ASIANPAINT', name: 'Asian Paints',                 sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'TITAN',      name: 'Titan Company',                sector: 'Consumer',       capType: 'Large Cap' },

  // ── NIFTY NEXT 50 ───────────────────────────────────────────────────────────

  { ticker: 'PIDILITIND',  name: 'Pidilite Industries',         sector: 'Chemicals',      capType: 'Large Cap' },
  { ticker: 'SIEMENS',     name: 'Siemens India',               sector: 'Infrastructure', capType: 'Large Cap' },
  { ticker: 'HAVELLS',     name: 'Havells India',               sector: 'Consumer',       capType: 'Large Cap' },
  { ticker: 'GODREJCP',    name: 'Godrej Consumer Products',    sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'DABUR',       name: 'Dabur India',                 sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'MARICO',      name: 'Marico',                      sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'COLPAL',      name: 'Colgate-Palmolive India',     sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'BRITANNIA',   name: 'Britannia Industries',        sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'TATACONSUM',  name: 'Tata Consumer Products',      sector: 'FMCG',           capType: 'Large Cap' },
  { ticker: 'UBL',         name: 'United Breweries',            sector: 'FMCG',           capType: 'Mid Cap' },
  { ticker: 'MUTHOOTFIN',  name: 'Muthoot Finance',             sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'CHOLAFIN',    name: 'Cholamandalam Finance',       sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'BAJAJHFL',    name: 'Bajaj Housing Finance',       sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'ICICIPRULI',  name: 'ICICI Prudential Life',       sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'ICICIGI',     name: 'ICICI Lombard General Ins',   sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'MANKIND',     name: 'Mankind Pharma',              sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'TORNTPHARM',  name: 'Torrent Pharmaceuticals',     sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'ALKEM',       name: 'Alkem Laboratories',          sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'LUPIN',       name: 'Lupin',                       sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'AUROPHARMA',  name: 'Aurobindo Pharma',            sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'BIOCON',      name: 'Biocon',                      sector: 'Pharma',         capType: 'Mid Cap' },
  { ticker: 'MAXHEALTH',   name: 'Max Healthcare',              sector: 'Healthcare',     capType: 'Large Cap' },
  { ticker: 'FORTIS',      name: 'Fortis Healthcare',           sector: 'Healthcare',     capType: 'Mid Cap' },
  { ticker: 'ZOMATO',      name: 'Zomato',                      sector: 'Tech',           capType: 'Large Cap' },
  { ticker: 'NYKAA',       name: 'FSN E-Commerce (Nykaa)',      sector: 'Tech',           capType: 'Mid Cap' },
  { ticker: 'PAYTM',       name: 'One 97 Communications',       sector: 'Fintech',        capType: 'Small Cap' },
  { ticker: 'POLICYBZR',   name: 'PB Fintech (Policybazaar)',   sector: 'Fintech',        capType: 'Mid Cap' },
  { ticker: 'DMART',       name: 'Avenue Supermarts (DMart)',   sector: 'Retail',         capType: 'Large Cap' },
  { ticker: 'TRENT',       name: 'Trent',                       sector: 'Retail',         capType: 'Large Cap' },
  { ticker: 'VEDL',        name: 'Vedanta',                     sector: 'Metals',         capType: 'Large Cap' },
  { ticker: 'SAIL',        name: 'Steel Authority of India',    sector: 'Metals',         capType: 'Mid Cap' },
  { ticker: 'NMDC',        name: 'NMDC',                        sector: 'Metals',         capType: 'Mid Cap' },
  { ticker: 'HINDCOPPER',  name: 'Hindustan Copper',            sector: 'Metals',         capType: 'Small Cap' },
  { ticker: 'DLF',         name: 'DLF',                         sector: 'Real Estate',    capType: 'Large Cap' },
  { ticker: 'GODREJPROP',  name: 'Godrej Properties',           sector: 'Real Estate',    capType: 'Large Cap' },
  { ticker: 'PRESTIGE',    name: 'Prestige Estates',            sector: 'Real Estate',    capType: 'Mid Cap' },
  { ticker: 'OBEROIRLTY',  name: 'Oberoi Realty',               sector: 'Real Estate',    capType: 'Mid Cap' },
  { ticker: 'INDIGO',      name: 'IndiGo (InterGlobe Aviation)', sector: 'Aviation',      capType: 'Large Cap' },
  { ticker: 'IRCTC',       name: 'IRCTC',                       sector: 'Infrastructure', capType: 'Large Cap' },
  { ticker: 'IRFC',        name: 'Indian Railway Finance Corp', sector: 'Finance',        capType: 'Large Cap' },
  { ticker: 'RVNL',        name: 'Rail Vikas Nigam',            sector: 'Infrastructure', capType: 'Mid Cap' },
  { ticker: 'BEL',         name: 'Bharat Electronics',          sector: 'Defence',        capType: 'Large Cap' },
  { ticker: 'HAL',         name: 'Hindustan Aeronautics',       sector: 'Defence',        capType: 'Large Cap' },
  { ticker: 'COCHINSHIP',  name: 'Cochin Shipyard',             sector: 'Defence',        capType: 'Small Cap' },
  { ticker: 'LTTS',        name: 'L&T Technology Services',     sector: 'IT',             capType: 'Large Cap' },
  { ticker: 'PERSISTENT',  name: 'Persistent Systems',          sector: 'IT',             capType: 'Large Cap' },
  { ticker: 'COFORGE',     name: 'Coforge',                     sector: 'IT',             capType: 'Mid Cap' },
  { ticker: 'MPHASIS',     name: 'Mphasis',                     sector: 'IT',             capType: 'Mid Cap' },
  { ticker: 'OFSS',        name: 'Oracle Financial Services',   sector: 'IT',             capType: 'Large Cap' },

  // ── NIFTY MIDCAP 50 ─────────────────────────────────────────────────────────

  { ticker: 'ABCAPITAL',   name: 'Aditya Birla Capital',        sector: 'Finance',        capType: 'Mid Cap' },
  { ticker: 'ABFRL',       name: 'Aditya Birla Fashion',        sector: 'Retail',         capType: 'Mid Cap' },
  { ticker: 'APOLLOTYRE',  name: 'Apollo Tyres',                sector: 'Auto',           capType: 'Mid Cap' },
  { ticker: 'ASHOKLEY',    name: 'Ashok Leyland',               sector: 'Auto',           capType: 'Mid Cap' },
  { ticker: 'BALKRISIND',  name: 'Balkrishna Industries',       sector: 'Auto',           capType: 'Mid Cap' },
  { ticker: 'BANDHANBNK',  name: 'Bandhan Bank',                sector: 'Banking',        capType: 'Mid Cap' },
  { ticker: 'BANKBARODA',  name: 'Bank of Baroda',              sector: 'Banking',        capType: 'Large Cap' },
  { ticker: 'CANBK',       name: 'Canara Bank',                 sector: 'Banking',        capType: 'Mid Cap' },
  { ticker: 'PNB',         name: 'Punjab National Bank',        sector: 'Banking',        capType: 'Mid Cap' },
  { ticker: 'FEDERALBNK',  name: 'Federal Bank',                sector: 'Banking',        capType: 'Mid Cap' },
  { ticker: 'IDFCFIRSTB',  name: 'IDFC First Bank',             sector: 'Banking',        capType: 'Mid Cap' },
  { ticker: 'KAJARIACER',  name: 'Kajaria Ceramics',            sector: 'Infrastructure', capType: 'Mid Cap' },
  { ticker: 'KPITTECH',    name: 'KPIT Technologies',           sector: 'IT',             capType: 'Mid Cap' },
  { ticker: 'LICHSGFIN',   name: 'LIC Housing Finance',         sector: 'Finance',        capType: 'Mid Cap' },
  { ticker: 'LODHA',       name: 'Macrotech Developers (Lodha)', sector: 'Real Estate',   capType: 'Large Cap' },
  { ticker: 'MAHABANK',    name: 'Bank of Maharashtra',         sector: 'Banking',        capType: 'Small Cap' },
  { ticker: 'MFSL',        name: 'Max Financial Services',      sector: 'Finance',        capType: 'Mid Cap' },
  { ticker: 'MOTHERSON',   name: 'Samvardhana Motherson',       sector: 'Auto',           capType: 'Large Cap' },
  { ticker: 'NBCC',        name: 'NBCC (India)',                 sector: 'Infrastructure', capType: 'Small Cap' },
  { ticker: 'NH',          name: 'Narayana Hrudayalaya',        sector: 'Healthcare',     capType: 'Mid Cap' },
  { ticker: 'PAGEIND',     name: 'Page Industries',             sector: 'Consumer',       capType: 'Mid Cap' },
  { ticker: 'PETRONET',    name: 'Petronet LNG',                sector: 'Energy',         capType: 'Mid Cap' },
  { ticker: 'PHOENIXLTD',  name: 'Phoenix Mills',               sector: 'Real Estate',    capType: 'Mid Cap' },
  { ticker: 'PIIND',       name: 'PI Industries',               sector: 'Chemicals',      capType: 'Mid Cap' },
  { ticker: 'POLYCAB',     name: 'Polycab India',               sector: 'Infrastructure', capType: 'Large Cap' },
  { ticker: 'SOLARINDS',   name: 'Solar Industries India',      sector: 'Defence',        capType: 'Mid Cap' },
  { ticker: 'SUNDARMFIN',  name: 'Sundaram Finance',            sector: 'Finance',        capType: 'Mid Cap' },
  { ticker: 'SUPREMEIND',  name: 'Supreme Industries',          sector: 'Chemicals',      capType: 'Mid Cap' },
  { ticker: 'TATACHEM',    name: 'Tata Chemicals',              sector: 'Chemicals',      capType: 'Mid Cap' },
  { ticker: 'TATACOMM',    name: 'Tata Communications',         sector: 'Telecom',        capType: 'Mid Cap' },
  { ticker: 'TATAELXSI',   name: 'Tata Elxsi',                  sector: 'IT',             capType: 'Mid Cap' },
  { ticker: 'TATAPOWER',   name: 'Tata Power',                  sector: 'Energy',         capType: 'Large Cap' },
  { ticker: 'TIINDIA',     name: 'Tube Investments of India',   sector: 'Auto',           capType: 'Mid Cap' },
  { ticker: 'TORNTPOWER',  name: 'Torrent Power',               sector: 'Energy',         capType: 'Mid Cap' },
  { ticker: 'TVSMOTOR',    name: 'TVS Motor Company',           sector: 'Auto',           capType: 'Large Cap' },
  { ticker: 'UPL',         name: 'UPL',                         sector: 'Chemicals',      capType: 'Mid Cap' },
  { ticker: 'VOLTAS',      name: 'Voltas',                      sector: 'Consumer',       capType: 'Mid Cap' },
  { ticker: 'WHIRLPOOL',   name: 'Whirlpool of India',          sector: 'Consumer',       capType: 'Small Cap' },
  { ticker: 'ZYDUSLIFE',   name: 'Zydus Lifesciences',          sector: 'Pharma',         capType: 'Large Cap' },
  { ticker: 'GMRINFRA',    name: 'GMR Airports Infrastructure', sector: 'Infrastructure', capType: 'Mid Cap' },
  { ticker: 'CONCOR',      name: 'Container Corp of India',     sector: 'Infrastructure', capType: 'Mid Cap' },
  { ticker: 'CUMMINSIND',  name: 'Cummins India',               sector: 'Infrastructure', capType: 'Mid Cap' },
  { ticker: 'SCHAEFFLER',  name: 'Schaeffler India',            sector: 'Auto',           capType: 'Mid Cap' },
  { ticker: 'SYNGENE',     name: 'Syngene International',       sector: 'Pharma',         capType: 'Mid Cap' },
  { ticker: 'IPCALAB',     name: 'IPCA Laboratories',           sector: 'Pharma',         capType: 'Mid Cap' },
  { ticker: 'LAUREATE',    name: 'Laurus Labs',                 sector: 'Pharma',         capType: 'Mid Cap' },
  { ticker: 'NATCOPHARM',  name: 'Natco Pharma',                sector: 'Pharma',         capType: 'Small Cap' },
  { ticker: 'AAVAS',       name: 'Aavas Financiers',            sector: 'Finance',        capType: 'Small Cap' },
  { ticker: 'CDSL',        name: 'CDSL',                        sector: 'Finance',        capType: 'Mid Cap' },
  { ticker: 'MCX',         name: 'Multi Commodity Exchange',    sector: 'Finance',        capType: 'Mid Cap' },
];

module.exports = STOCK_UNIVERSE;